name: stripe_transform
version: '1.0'
config-version: 2
profile: stripe_bigquery
model-paths: [models]
analysis-paths: [analysis]
target-path: target
clean-targets: ['target', 'dbt_packages']
log-path: logs
packages-install-path: dbt_packages

models:
  stripe_transform:
    staging_stripe:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts