name: stripe_transform
version: '1.0'
config-version: 2
profile: stripe_bigquery
source-paths: [models]
analysis-paths: [analysis]
target-path: target
clean-targets: ['target', 'dbt_modules']

models:
  stripe_transform:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table 