version: 2

models:
  - name: charges_view
    description: "Cast and clean charge data for BigQuery"
    columns:
      - name: id
        description: "Primary identifier for the charge"
        tests:
          - not_null
          - unique
      - name: amount
        description: "Amount intended to be collected (in cents)"
        tests:
          - not_null

  - name: coupons
    description: "Cast and clean coupon data for BigQuery"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: stripe_id
        tests:
          - not_null

  - name: customers_view
    description: "Cast and clean customer data for BigQuery"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: stripe_id
        tests:
          - not_null

  - name: invoices_view
    description: "Cast and clean invoice data for BigQuery"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: stripe_id
        tests:
          - not_null

  - name: payment_intents_view
    description: "Cast and clean payment intent data for BigQuery"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: stripe_id
        tests:
          - not_null

  - name: plans
    description: "Cast and clean subscription plan data for BigQuery"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: stripe_id
        tests:
          - not_null

  - name: prices
    description: "Cast and clean pricing data for BigQuery"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: stripe_id
        tests:
          - not_null

  - name: products
    description: "Cast and clean product data for BigQuery"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: stripe_id
        tests:
          - not_null

  - name: refunds
    description: "Cast and clean refund data for BigQuery"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: stripe_id
        tests:
          - not_null

  - name: subscriptions
    description: "Cast and clean subscription data for BigQuery"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: stripe_id
        tests:
          - not_null 